# Generated by Django 3.2 on 2022-01-18 00:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documentType', models.CharField(max_length=150)),
                ('documentId', models.IntegerField()),
                ('firstName', models.CharField(max_length=150)),
                ('SecondName', models.CharField(max_length=150)),
                ('firstSurname', models.CharField(max_length=150)),
                ('secondSurname', models.CharField(max_length=150)),
                ('pathologies', models.ManyToManyField(to='api.Pathology')),
            ],
        ),
    ]
