# Generated by Django 3.2 on 2022-01-18 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='SecondName',
            new_name='secondName',
        ),
    ]
