# Generated by Django 3.2 on 2022-01-19 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_secondname_patient_secondname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pathology',
            options={},
        ),
        migrations.AlterField(
            model_name='patient',
            name='pathologies',
            field=models.ManyToManyField(blank=True, to='api.Pathology'),
        ),
    ]
