# Generated by Django 3.2 on 2022-01-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220118_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='firstName',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='firstSurname',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='secondName',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='patient',
            name='secondSurname',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
